### ISSUE TITLE
Variables for 4.2 are using beta repos.

### ISSUE THREAD

**Issue by petr-balogh** [oVirt/ovirt-ansible-repositories#18]
When I am looking to variable files for engine and host for 4.2 I see:

# FIXME These are for 4.2 BETA
ovirt_repositories_subscription_manager_repos:
  - rhel-7-server-rpms
  - rhel-7-server-supplementary-rpms
  - rhel-7-server-rhv-4-beta-rpms
  - rhel-7-server-rhv-4-tools-beta-rpms
  - jb-eap-7-for-rhel-7-server-rpms

I guess they should be changed to not using beta here.

**Comment by mwperina** [comment]
Where do you see those? Channels mentioned in https://github.com/oVirt/ovirt-ansible-repositories/blob/master/vars/engine_4.2.yml seems correct to me and I have't found any files with 'beta' string

**Comment by petr-balogh** [comment]
Sorry I was from some reason on different tree view https://github.com/oVirt/ovirt-ansible-repositories/tree/491ffa3da92ea05e4ba4282da9726f6d24547329
