### ISSUE TITLE
subscribtion manager support in guest

### ISSUE THREAD

**Issue by mgoldboi** [oVirt/ovirt-ansible-repositories#22]
Hi, would be awesome if this role could be used in the context of registering the guest (vm) to subscription manager, perhaps openstack role (https://github.com/openstack/ansible-role-redhat-subscription)logic could be used here as well.

**Comment by machacekondra** [comment]
@mnecas

**Comment by mwperina** [comment]
Closing as deferred, we don't see any interest from users about this issue
